sudo: required

env:
  global:
    - VERSION="2018.3"
    - BUILD="${VERSION}.${TRAVIS_BUILD_NUMBER}"
    - secure: "BU6qOLe+/3SunZygJZO98o/SgUn4EgRHPu95hbXtGwJeAjJX57BtivSOVjdIX+EHEuAybgtbY6ckVHfx0n8zDNTHfyotLbyWK8XKW91AVk882/rLNMDLKIJ1o396dWLZ0nIlE4uAn8M8YNHBChnkkeIKTxH0+OwS2jRpxNTD3Z5KPS8AKuqzscwkm9FA/XxjR8XQLXcnCsiCkhf0/RA9tmve01qRZX5PkHpHXJk69ZGhbqEhphRTkSbtvrTlOVrwAQnsqMvGyzl2efp47VPwEdk4feNnoGbhi9npGRTKA2l79Y+RJZAMz+SGmxgrSNOxJOTIBiPNeTd9iOuturNpwnBV04Gx4NK6DA1rrXtu1GhKWjiyTDOz9LVo2060F1QhexfKKlXeL9JwQNPd1mrqVP9cvUbNcexJQ2bQVfb6/6iZgDXslAKe1UYdjCPLUg5R0Ls4God8YESr9ZMo3AdK1D+xh5Odi6Eff4BJ/jvmf219zQg+vpZRd9EDQJJkZ7B7kCPPOUBS+l5PZ8dfzf/0rsGCLkNq6Cz8uEu6iX72Ua4sP9P7Clt6X8ypEnZp7t6zhpsIcE/yp2lvJhvEfBWdUrR7aUC8EB0d7TOl3uMmSoFo890wiUQeKJUqqE92PcBxKkmqpHGvR6Nw+fg6mvCcArwA1UKgKkBi08Og4u4ZOjQ="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: eprikazchikov/thunder
      description: Light Weight Game Engine
    notification_email: eprikazchikov@mail.ru
    build_command_prepend: qbs config defaultProfile qt-5-10-1
    build_command: qbs build --all-products config:release
    branch_pattern: coverity_scan

matrix:
  include:
    - language: cpp
      os: linux
      dist: trusty
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
        - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
        - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get -y install qt510base qt510multimedia qt510script qt510svg qt510imageformats qt510graphicaleffects qt510quickcontrols2 qt510tools binutils zlib1g-dev xorg-dev gcc-7 g++-7
        - source /opt/qt510/bin/qt510-env.sh
        - wget https://github.com/eprikazchikov/dependencies/releases/download/qbs-1.11.0/qbs-1.11.0-linux.tar.gz
        - tar -xvzf qbs-1.11.0-linux.tar.gz > /dev/null
        - export PATH=$PATH:qbs-build/bin
        - qbs --version
        - qbs setup-toolchains --detect
        - qbs setup-qt --detect
      script:
        - qbs config defaultProfile qt-5-10-1
        - qbs config --list
        - qbs install --all-products config:release
        - tar -zcvf ThunderEngine-linux-x86_64.tar.gz release/install-root/sdk/${VERSION}/linux
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl --upload-file ThunderEngine-linux-x86_64.tar.gz https://transfer.sh/ThunderEngine-${BUILD}-linux-x86_64.tar.gz
          on:
            tags: true

    - language: cpp
      os: osx
      osx_image: xcode9.3
      before_install:
        - brew update
        - brew install qbs
        - qbs --version
        - qbs setup-toolchains --detect
        - qbs setup-qt /usr/local/opt/qt/bin/qmake qt-brew
      script:
        - qbs config --list
        - qbs install --all-products config:release profile:qt-brew
        - /usr/local/opt/qt/bin/macdeployqt release/install-root/sdk/${VERSION}/macos/x86_64/bin/WorldEditor.app/ -executable=release/install-root/sdk/${VERSION}/macos/x86_64/bin/WorldEditor.app/Contents/MacOS/Builder
        - tar -zcvf ThunderEngine-macosx-x86_64.tar.gz release/install-root/sdk/${VERSION}/macos
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl --upload-file ThunderEngine-macosx-x86_64.tar.gz https://transfer.sh/ThunderEngine-${BUILD}-macos-x86_64.tar.gz
          on:
            tags: true

    - language: cpp
      os: osx
      osx_image: xcode9.3
      before_install:
        - brew update
        - brew install qbs
        - qbs --version
        - qbs setup-toolchains --detect
        - qbs setup-qt /usr/local/opt/qt/bin/qmake qt-brew
      script:
        - qbs config --list
        - qbs install --all-products config:release profile:xcode-iphoneos-arm64
        - tar -zcvf ThunderEngine-ios-arm64.tar.gz release/install-root/sdk/${VERSION}/ios
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl --upload-file ThunderEngine-ios-arm64.tar.gz https://transfer.sh/ThunderEngine-${BUILD}-ios-arm64.tar.gz
          on:
            tags: true
    - language: cpp
      os: osx
      osx_image: xcode9.3
      before_install:
        - brew update
        - brew install qbs
        - qbs --version
        - qbs setup-toolchains --detect
        - qbs setup-qt /usr/local/opt/qt/bin/qmake qt-brew
      script:
        - qbs config --list
        - qbs install --all-products config:release profile:xcode-appletvos-arm64
        - tar -zcvf ThunderEngine-tvos-arm64.tar.gz release/install-root/sdk/${VERSION}/tvos
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl --upload-file ThunderEngine-tvos-arm64.tar.gz https://transfer.sh/ThunderEngine-${BUILD}-tvos-arm64.tar.gz
          on:
            tags: true
        
    #- lanuage: android
    #  os: linux
    #  jdk: oraclejdk8
    #  android:
    #    components:
    #      - tools
    #      - android-25
    #      - build-tools-25.0.3
    #  before_install:
    #    - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
    #    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    #    - sudo apt-get update -qq
    #    - sudo apt-get -y install qt510base qt510script qt510svg qt510imageformats qt510tools binutils zlib1g-dev xorg-dev gcc-7 g++-7
    #    - source /opt/qt510/bin/qt510-env.sh
    #    - wget https://github.com/eprikazchikov/dependencies/releases/download/qbs-1.11.0/qbs-1.11.0-linux.tar.gz
    #    - tar -xvzf qbs-1.11.0-linux.tar.gz
    #    - export PATH=$PATH:qbs-build/bin
    #    - qbs --version
    #    - qbs setup-toolchains --detect
    #    - qbs setup-qt --detect
